Repository magickasoft/fit-paradise, pull requests merged in 2025-08, with the labels that each got.

#74 fix
  messages/ru.d.json.ts
Labels: Review effort 1/5

#75 Feature/#53
  src/app/[locale]/layout.tsx
  src/app/[locale]/recipe/[name]/page.tsx
  src/app/globals-styles.ts
  src/app/globals.css
  src/app/layout.tsx
  src/components/RecipePage/RecipePage.tsx
  src/constants.ts/recipes/breakfast.ts
  src/constants.ts/recipes/dessert.ts
  src/constants.ts/recipes/dinner.ts
  src/constants.ts/recipes/grill.ts
  src/constants.ts/recipes/healthy.ts
  src/constants.ts/recipes/snacks.ts
  src/constants.ts/recipes/summer-menu.ts
  src/constants.ts/recipes/supper.ts
  src/helpers/findByKey.ts
Labels: Review effort 4/5

#78 Feature/#66
  bun.lockb
  package.json
  public/static/equipments/wooden-spoon.jpg
  public/static/ingredients/canned-beans.jpeg
  public/static/ingredients/chili-pepper.jpeg
  public/static/ingredients/cumin.jpg
  public/static/ingredients/dried-mint.jpg
  public/static/ingredients/green-pepper.jpg
  public/static/ingredients/milk-sausages.jpeg
  public/static/ingredients/red-pepper-flakes.jpg
  public/static/ingredients/smoked-paprika.jpeg
  public/static/ingredients/tomato-paste.jpg
  public/static/ingredients/worcestershire-sauce.jpeg
  public/static/recipes/breakfast/menemen.jpeg
  public/static/recipes/breakfast/scrambled-eggs-shakshuka.jpeg
  public/static/recipes/breakfast/scrambled-eggs-with-sausages-and-beans.jpeg
  src/components/Cards/DetailCards.tsx
  src/components/Header.tsx
  src/components/RecipePage/RecipePage.tsx
  src/constants.ts/equipments.ts
  src/constants.ts/ingredients.ts
  src/constants.ts/recipes/breakfast.ts
  src/constants.ts/recipes/recipes.ts
  src/jsons/equipments/wooden-spoon.json
  src/jsons/ingredients/liquid/worcestershire-sauce.json
  src/jsons/ingredients/meat/milk-sausages.json
  src/jsons/ingredients/seasoning/cumin.json
  src/jsons/ingredients/seasoning/dried-mint.json
  src/jsons/ingredients/seasoning/red-pepper-flakes.json
  src/jsons/ingredients/seasoning/smoked-paprika.json
  src/jsons/ingredients/vegetables/canned-beans.json
  src/jsons/ingredients/vegetables/chili-pepper.json
  src/jsons/ingredients/vegetables/green-pepper.json
  src/jsons/ingredients/vegetables/tomato-paste.json
Labels: Review effort 4/5

#80 add new recipes
  public/static/recipes/dinner/classic-borscht.jpeg
  public/static/recipes/dinner/cream-mushroom-soup.jpeg
  public/static/recipes/dinner/gazpacho.jpeg
  public/static/recipes/dinner/pho-bo.jpeg
  public/static/recipes/dinner/pumpkin-cream-soup.jpeg
  src/constants.ts/recipes/dinner.ts
Labels: Review effort 3/5

#82 Feature/#81
  public/static/recipes/dessert/beze.jpeg
  public/static/recipes/dessert/chocolate-truffles.jpeg
  public/static/recipes/dessert/klubnichnyy-pai-s-pesochnoy-kroschkoy.jpeg
  public/static/recipes/dessert/krem-bryule-s-vanilyu.jpeg
  public/static/recipes/dessert/lenivyy-napoleon.jpeg
  public/static/recipes/dessert/meringue-roll-s-lemon-curd.jpeg
  public/static/recipes/dessert/morkovnyy-tort-s-gretskimi-orekhami.jpeg
  public/static/recipes/dessert/panna-cotta.jpeg
  public/static/recipes/dessert/pirozhnoye-kartoshka.jpeg
  public/static/recipes/dessert/shu-s-kremom.jpeg
  public/static/recipes/dessert/tort-medovik.jpeg
  src/app/[locale]/layout.tsx
  src/app/[locale]/page.tsx
  src/components/Footer.tsx
  src/constants.ts/recipes/dessert.ts
Labels: Review effort 2/5

#88 add new recipes
  public/static/recipes/dessert/apple-strudel.jpeg
  public/static/recipes/dessert/cherry-pie.jpeg
  public/static/recipes/grill/shashlyk-iz-kuritsy-v-kefirnom-marinade.jpeg
  public/static/recipes/grill/shashlyk-iz-kuritsy-v-soevom-marinade.jpeg
  src/constants.ts/recipes/dessert.ts
  src/constants.ts/recipes/grill.ts
Labels: Review effort 3/5

#90 add new recipes
  public/static/recipes/grill/gril-sendvich-s-halloumi-i-ovoschami.jpeg
  public/static/recipes/grill/krevetki-na-grile-s-chesnochnym-maslom.jpeg
  public/static/recipes/grill/losos-na-kedrovoy-doske-s-medovo-gorchichnym-sousom.jpeg
  public/static/recipes/grill/ovoschi-gril-s-balzamisceskoy-glazuryu.jpeg
  public/static/recipes/grill/shashlyk-iz-baraniny-s-rozmarinom.jpeg
  public/static/recipes/grill/shashlyk-iz-indeyki-v-yogurtovom-marinade.jpeg
  public/static/recipes/grill/shashlyk-iz-svininy-v-granatovom-souse.jpeg
  src/constants.ts/recipes/grill.ts
Labels: Review effort 2/5

#91 fixes
  bun.lockb
  next.config.ts
  src/app/[locale]/layout.tsx
  src/app/layout.tsx
Labels: Review effort 2/5

#92 add localeSelect component
  messages/en.json
  messages/ru.d.json.ts
  messages/ru.json
  src/components/Header.tsx
  src/components/LocaleSelect.tsx
  src/components/LocaleSwitcher.tsx
Labels: Review effort 2/5

#94 add new
  messages/en.json
  messages/ru.d.json.ts
  messages/ru.json
  public/static/recipes/healthy/farshirovannye-pertsy-s-kinoa.jpeg
  public/static/recipes/healthy/kinoa-boul-s-lososem.jpeg
  public/static/recipes/healthy/smuzi-boul-s-chia.jpeg
  public/static/recipes/healthy/tykvennyj-sup-s-imbirem.jpeg
  public/static/recipes/salads/grecheskij-salat.jpeg
  public/static/recipes/salads/gruzinskii-salat-lobio.jpeg
  public/static/recipes/salads/krabovyi-salat-s-kukuruzoi.jpeg
  public/static/recipes/salads/letnii-salat-s-klubnikoi.jpeg
  public/static/recipes/salads/salat-cezar-s-kuritsey.jpeg
  public/static/recipes/salads/salat-kapreze.jpeg
  public/static/recipes/salads/salat-nisuaz-s-tuntsom.jpeg
  public/static/recipes/salads/salat-olivye-klassicheskii.jpeg
  public/static/recipes/salads/salat-s-avokado-i-krevetkami.jpeg
  public/static/recipes/salads/salat-s-tuntsom-i-yaitsom.jpeg
  public/static/recipes/salads/salat-valdorf-s-kuritsey.jpeg
  public/static/recipes/salads/teplyj-salat-s-govyadinoj.jpeg
  public/static/recipes/snacks/grecheskiy-sendvich-s-fetoy.jpeg
  public/static/recipes/snacks/sendvich-s-avokado-i-yaitsom-pashot.jpeg
  public/static/recipes/snacks/sendvich-s-kuritsey-i-pesto.jpeg
  public/static/recipes/supper/kuritsa-gril-s-kinoa.jpeg
  public/static/recipes/supper/losos-v-medovo-gorchichnom-souse.jpeg
  public/static/recipes/supper/ratatui-s-baklazhanami.jpeg
  public/static/seasonal-categories/salads.png
  src/components/LocaleSelect.tsx
  src/components/SeasonalCategories/constants.ts
  src/constants.ts/recipes/healthy.ts
  src/constants.ts/recipes/recipes.ts
  src/constants.ts/recipes/salads.ts
  src/constants.ts/recipes/snacks.ts
  src/constants.ts/recipes/summer-menu.ts
  src/constants.ts/recipes/supper.ts
Labels: Review effort 4/5

#100 Add new recipes
  public/static/recipes/dinner/kurinyy-bulon-s-lapshoy.jpeg
  public/static/recipes/dinner/schi-iz-svezhey-kapusty.jpeg
  public/static/recipes/dinner/sup-pyure-iz-tykvy.jpeg
  public/static/recipes/dinner/uha-po-finski.jpeg
  public/static/recipes/supper/farshirovannye-pertsy.jpeg
  public/static/recipes/supper/govyadina-po-burgundski.jpeg
  public/static/recipes/supper/grechka-s-gribami-i-lukom.jpeg
  public/static/recipes/supper/kartofelnaya-zapekanka-s-farshem.jpeg
  public/static/recipes/supper/kotlety-s-pyure.jpeg
  public/static/recipes/supper/krevetki-v-chesnochnom-souse.jpeg
  public/static/recipes/supper/kurinye-grudki-v-slivocnom-souse.jpeg
  public/static/recipes/supper/lazanya-s-myasom-i-syrom.jpeg
  public/static/recipes/supper/losos-pod-syrnoy-korochkoy.jpeg
  public/static/recipes/supper/makarony-s-syrom.jpeg
  public/static/recipes/supper/ratatuy-po-domashnemu.jpeg
  public/static/recipes/supper/rybnye-kotlety-s-pyure.jpeg
  src/constants.ts/recipes/dinner.ts
  src/constants.ts/recipes/supper.ts
Labels: Review effort 3/5

#107 complexity
  src/i18n/constants.ts
  src/i18n/getUrlLocale.ts
  src/i18n/isSupportedLocale.ts
Labels: Review effort 2/5

#109 Feature/complexity2
  src/i18n/getBrowserLocale.ts
Labels: Review effort 2/5

#112 Update findByKey.ts
  src/helpers/findByKey.ts
Labels: Review effort 2/5

#111 Feature/#106
  public/static/categories-imgs/breakfast.jpeg
  public/static/categories-imgs/desserts.jpeg
  public/static/categories-imgs/dinner.jpeg
  public/static/categories-imgs/grill.jpeg
  public/static/categories-imgs/healthy.jpeg
  public/static/categories-imgs/refreshingDrinks.jpeg
  public/static/categories-imgs/salads.jpeg
  public/static/categories-imgs/snacks.jpeg
  public/static/categories-imgs/supper.jpeg
  public/static/main-page-imgs/breakfast.png
  public/static/main-page-imgs/desserts.png
  public/static/main-page-imgs/dinner.png
  public/static/main-page-imgs/drinks.png
  public/static/main-page-imgs/healthy.png
  public/static/main-page-imgs/snacks.png
  public/static/main-page-imgs/supper.png
  public/static/recipes/refreshingDrinks/arbuznyj-smuzi.jpeg
  public/static/recipes/refreshingDrinks/imbirnyj-limonad-s-medom.jpeg
  public/static/recipes/refreshingDrinks/inzhirnyj-koktejl.jpeg
  public/static/recipes/refreshingDrinks/klubnichno-bazilikovyj-limonad.jpeg
  public/static/recipes/refreshingDrinks/limonad-s-myatoj.jpeg
  public/static/recipes/refreshingDrinks/malinovyj-chajnyj-fresh.jpeg
  public/static/recipes/refreshingDrinks/myatno-limonnij-detoks-napitok.jpeg
  public/static/recipes/refreshingDrinks/ogurechno-lajmovyj-spritser.jpeg
  public/static/recipes/refreshingDrinks/ogurechnyj-detoks-napitok.jpeg
  public/static/recipes/refreshingDrinks/persikovyj-latte.jpeg
  public/static/recipes/refreshingDrinks/tropicheskij-smuzi-s-mango.jpeg
  public/static/recipes/refreshingDrinks/yagodnyj-mors.jpeg
  public/static/seasonal-categories/grill.png
  public/static/seasonal-categories/salads.png
  src/components/Cards/CategoryCard.tsx
  src/components/Cards/RecipeCard.tsx
  src/components/Header.tsx
  src/components/LocaleSelect.tsx
  src/components/PopularCategories/PopularCategories.tsx
  src/components/PopularCategories/constants.ts
  src/components/RecipePage/RecipePage.tsx
  src/components/SeasonalCategories/SeasonalCategories.tsx
  src/components/SeasonalCategories/constants.ts
  src/constants/recipes/recipes.ts
  src/constants/recipes/refreshingDrinks.ts
Labels: Review effort 3/5

#121 up lib
  bun.lockb
  package.json
  src/app/[locale]/layout.tsx
Labels: Review effort 2/5
